<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="11" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Automation Test Suite for IX Onespace" duration-ms="43520" started-at="2020-08-15T14:12:27Z" finished-at="2020-08-15T14:13:11Z">
    <groups>
      <group name="SmokeSuite">
        <method signature="test.verifyGetUserStatusCode()[pri:0, instance:apitest.test@18eed359]" name="verifyGetUserStatusCode" class="apitest.test"/>
      </group> <!-- SmokeSuite -->
    </groups>
    <test name="Automation Test Cases" duration-ms="43520" started-at="2020-08-15T14:12:27Z" finished-at="2020-08-15T14:13:11Z">
      <class name="apitest.test">
        <test-method status="PASS" signature="postMethodValidationDataFile()[pri:0, instance:apitest.test@18eed359]" name="postMethodValidationDataFile" duration-ms="26952" started-at="2020-08-15T19:42:27Z" description="validate with jsonpath and json object and pass post body as json file" finished-at="2020-08-15T19:42:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postMethodValidationDataFile -->
        <test-method status="PASS" signature="postmethodjson()[pri:0, instance:apitest.test@18eed359]" name="postmethodjson" duration-ms="5096" started-at="2020-08-15T19:42:54Z" description="Automate post method for users" finished-at="2020-08-15T19:42:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postmethodjson -->
        <test-method status="PASS" signature="postmethodwithpojoclass()[pri:0, instance:apitest.test@18eed359]" name="postmethodwithpojoclass" duration-ms="3938" started-at="2020-08-15T19:42:59Z" finished-at="2020-08-15T19:43:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postmethodwithpojoclass -->
        <test-method status="PASS" signature="putmethodjson()[pri:0, instance:apitest.test@18eed359]" name="putmethodjson" duration-ms="1424" started-at="2020-08-15T19:43:04Z" description="Automate post method for users" finished-at="2020-08-15T19:43:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- putmethodjson -->
        <test-method status="SKIP" signature="verifyEmailUID()[pri:0, instance:apitest.test@18eed359]" name="verifyEmailUID" duration-ms="1066" started-at="2020-08-15T19:43:05Z" description="Verify email for User with id=2" finished-at="2020-08-15T19:43:06Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [21]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [21]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:132)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at apitest.test.verifyEmailUID(test.java:138)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmailUID -->
        <test-method status="SKIP" signature="verifyEmailUID()[pri:0, instance:apitest.test@18eed359]" name="verifyEmailUID" duration-ms="657" started-at="2020-08-15T19:43:06Z" description="Verify email for User with id=2" finished-at="2020-08-15T19:43:07Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [21]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [21]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:132)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at apitest.test.verifyEmailUID(test.java:138)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmailUID -->
        <test-method status="FAIL" signature="verifyEmailUID()[pri:0, instance:apitest.test@18eed359]" name="verifyEmailUID" duration-ms="819" started-at="2020-08-15T19:43:07Z" description="Verify email for User with id=2" finished-at="2020-08-15T19:43:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [null] but found [21]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [null] but found [21]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:132)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at apitest.test.verifyEmailUID(test.java:138)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.retryFailed(Invoker.java:829)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1000)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmailUID -->
        <test-method status="PASS" signature="verifyEmailUID2()[pri:0, instance:apitest.test@18eed359]" name="verifyEmailUID2" duration-ms="1011" started-at="2020-08-15T19:43:08Z" description="Verify email for User with id=2" finished-at="2020-08-15T19:43:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmailUID2 -->
        <test-method status="PASS" signature="verifyEmailUIDheaders()[pri:0, instance:apitest.test@18eed359]" name="verifyEmailUIDheaders" duration-ms="733" started-at="2020-08-15T19:43:09Z" description="Verify email for User with id=2" finished-at="2020-08-15T19:43:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEmailUIDheaders -->
        <test-method status="PASS" signature="verifyGetUserStatusCode()[pri:0, instance:apitest.test@18eed359]" name="verifyGetUserStatusCode" duration-ms="513" started-at="2020-08-15T19:43:09Z" description="Validate 404 status code - GET API" finished-at="2020-08-15T19:43:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyGetUserStatusCode -->
        <test-method status="PASS" signature="verifyStatusCodeDelete()[pri:0, instance:apitest.test@18eed359]" name="verifyStatusCodeDelete" duration-ms="851" started-at="2020-08-15T19:43:10Z" description="validate 204 for Delete user" finished-at="2020-08-15T19:43:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyStatusCodeDelete -->
      </class> <!-- apitest.test -->
    </test> <!-- Automation Test Cases -->
  </suite> <!-- Automation Test Suite for IX Onespace -->
</testng-results>
